version: '3.7'
services:
    web:
        build: .
        image: redis-task
        ports:
            - "5000:5000"
        depends_on:
            - redis
        command: python app.py run -h 0.0.0.0
    redis:
        image: "redis"
        ports:
            - "6379:6379"